apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  externalIPs:
  - 192.168.99.102
  selector:
    service: backend-user