apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  externalIPs:
  - 192.168.99.102
  selector:
    service: frontend
#  type: LoadBalancer    
