apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  externalIPs:
  - 192.168.99.102
  selector:
    service: reverseproxy
#  type: LoadBalancer    
