version: "3"
services:
 reverseproxy:
  build:
    context: .
  image: arjun21/reverseproxy 
 backend_user:
  build:
    context: ../../udacity-c3-restapi-user
  image: arjun21/udacity-restapi-user
 backend_feed:
  build:
    context: ../../udacity-c3-restapi-feed 
  image: arjun21/udacity-restapi-feed
 frontend:
  build:
    context: ../../udacity-c3-frontend 
  image: arjun21/udacity-frontend:local